UPDATE content_items
SET title_key = lower(
  replace(
    replace(
      replace(
        replace(
          replace(
            replace(
              replace(
                replace(
                  replace(
                    replace(
                      replace(
                        replace(
                          replace(
                            replace(
                              replace(
                                replace(
                                  replace(
                                    replace(
                                      replace(
                                        replace(title, ' ', ''),
                                        '　',
                                        ''
                                      ),
                                      '?',
                                      ''
                                    ),
                                    '？',
                                    ''
                                  ),
                                  '!',
                                  ''
                                ),
                                '！',
                                ''
                              ),
                              ',',
                              ''
                            ),
                            '，',
                            ''
                          ),
                          '.',
                          ''
                        ),
                        '。',
                        ''
                      ),
                      ':',
                      ''
                    ),
                    '：',
                    ''
                  ),
                  '"',
                  ''
                ),
                '''',
                ''
              ),
              '`',
              ''
            ),
            '(',
            ''
          ),
          ')',
          ''
        ),
        '（',
        ''
      ),
      '）',
      ''
    ),
    '、',
    ''
  )
)
WHERE title_key = '';
